// FIND DIFFERENCE

/*
Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s 
and then add one more letter at a random position.

Find the letter that was added in t.

    Example:

    Input:
    s = "abcd"
    t = "abcde"

    Output:
    e

    Explanation:
    'e' is the letter that was added.
*/

var findTheDifference = function(s, t) {
/*
FIRST WAY OF SOLVING THROUGH CACHING LETTERS WITH COUNT OF APPEARANCES
AND THEN SUBTRACTING TO FIND EITHER THE UNAPPEARED LETTER OR THE EXTRA

    let memo = {};
    for(let letter of s){
        if(memo[letter]){
            memo[letter]++;
        }
        else memo[letter] = 1
    }
    for(let letter of t) {
        if(!memo[letter]) return letter
        else {
            memo[letter]--;
        }
    }
    for(let [key, value] of memo.entries()){
        if(value < 0) return key
    }
*/

// SECOND SOLUTION
// sorts both words and loops through for the mis-alignment
// same time complexity on best case scenario of solution #1 
// but better space complexity
    s = s.split('').sort()
    t = t.split('').sort()
    for(let i = 0; i < t.length; i++) {
        if(t[i] !== s[i]){
            return t[i]
        }
    }
};

const str1 = 'abcdefghijklmnopqrs';
const str2 = 'zsrqponmlkjihgfedcba';
const result = findTheDifference(str1, str2);
console.log(result);